# Generated by cpp11: do not edit by hand

FindPredictiveDensityAndCIWalker <- function(calendar_ages, weights, phis, taus, mu_phis, lambda, nu1, nu2, n_posterior_samples, quantile_edge_width) {
  .Call(`_carbondate_FindPredictiveDensityAndCIWalker`, calendar_ages, weights, phis, taus, mu_phis, lambda, nu1, nu2, n_posterior_samples, quantile_edge_width)
}

FindPredictiveDensityandCIPolyaUrn <- function(calendar_ages, observations_per_clusters, phis, taus, alphas, mu_phis, n_obs, lambda, nu1, nu2, n_posterior_samples, quantile_edge_width) {
  .Call(`_carbondate_FindPredictiveDensityandCIPolyaUrn`, calendar_ages, observations_per_clusters, phis, taus, alphas, mu_phis, n_obs, lambda, nu1, nu2, n_posterior_samples, quantile_edge_width)
}

PolyaUrnUpdateAlpha_test <- function(n, nci, current_alpha, alpha_shape, alpha_rate) {
  .Call(`_carbondate_PolyaUrnUpdateAlpha_test`, n, nci, current_alpha, alpha_shape, alpha_rate)
}

PolyaUrnUpdateStep <- function(current_calendar_ages, current_cluster_ids, current_phi, current_tau, current_alpha, current_mu_phi, alpha_shape, alpha_rate, lambda, nu1, nu2, A, B, w, m, c14_determinations, c14_sigmas, mucalallyr, sigcalallyr) {
  .Call(`_carbondate_PolyaUrnUpdateStep`, current_calendar_ages, current_cluster_ids, current_phi, current_tau, current_alpha, current_mu_phi, alpha_shape, alpha_rate, lambda, nu1, nu2, A, B, w, m, c14_determinations, c14_sigmas, mucalallyr, sigcalallyr)
}

WalkerUpdateStep <- function(current_calendar_ages, current_weight, current_v, current_cluster_ids, current_n_clust, current_alpha, current_mu_phi, alpha_shape, alpha_rate, lambda, nu1, nu2, A, B, w, m, c14_determinations, c14_sigmas, mucalallyr, sigcalallyr) {
  .Call(`_carbondate_WalkerUpdateStep`, current_calendar_ages, current_weight, current_v, current_cluster_ids, current_n_clust, current_alpha, current_mu_phi, alpha_shape, alpha_rate, lambda, nu1, nu2, A, B, w, m, c14_determinations, c14_sigmas, mucalallyr, sigcalallyr)
}
